### ISSUE TITLE
Facing issue installing package

### ISSUE THREAD

**Issue by abhishekscript** [philipperemy/Stanford-OpenIE-Python#1]
Hi,
tried to install as per instruction and got the following error
`tanford-openie.jar              100%[========================================================>]   6.40M  1.09MB/s    in 11s     

2016-12-23 16:57:38 (620 KB/s) - ‘stanford-openie.jar’ saved [6711389/6711389]

--2016-12-23 16:57:38--  http://nlp.stanford.edu/projects/naturalli/stanford-openie-models.jar
Resolving nlp.stanford.edu... 171.64.67.140
Connecting to nlp.stanford.edu|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 60573385 (58M) [application/x-java-archive]
Saving to: ‘stanford-openie-models.jar’

stanford-openie-models.jar       100%[========================================================>]  57.77M  4.19MB/s    in 30s     

2016-12-23 16:58:09 (1.90 MB/s) - ‘stanford-openie-models.jar’ saved [60573385/60573385]

Namespace(filename='samples.txt', generate_graph=False, verbose=True)
filename = samples.txt
Executing command = cd /Users/abhishekrana/Documents/Stanford-OpenIE-Python/;cd stanford-openie; java -mx4g -cp "stanford-openie.jar:stanford-openie-models.jar:lib/*" edu.stanford.nlp.naturalli.OpenIE ../samples.txt  -format ollie > /tmp/openie/out.txt
Exception in thread "main" java.lang.ExceptionInInitializerError
	at edu.stanford.nlp.naturalli.OpenIE.<clinit>(OpenIE.java:80)
Caused by: java.lang.IllegalStateException: Could not find SLF4J in your classpath
	at edu.stanford.nlp.util.logging.RedwoodConfiguration$Handlers.lambda$static$460(RedwoodConfiguration.java:189)
	at edu.stanford.nlp.util.logging.RedwoodConfiguration$Handlers$7.buildChain(RedwoodConfiguration.java:298)
	at edu.stanford.nlp.util.logging.RedwoodConfiguration$Handlers$7.apply(RedwoodConfiguration.java:307)
	at edu.stanford.nlp.util.logging.RedwoodConfiguration.lambda$handlers$465(RedwoodConfiguration.java:352)
	at edu.stanford.nlp.util.logging.RedwoodConfiguration.apply(RedwoodConfiguration.java:41)
	at edu.stanford.nlp.util.logging.Redwood.<clinit>(Redwood.java:609)
	... 1 more
Caused by: edu.stanford.nlp.util.MetaClass$ClassCreationException: java.lang.ClassNotFoundException: edu.stanford.nlp.util.logging.SLF4JHandler
	at edu.stanford.nlp.util.MetaClass.createFactory(MetaClass.java:362)
	at edu.stanford.nlp.util.MetaClass.createInstance(MetaClass.java:379)
	at edu.stanford.nlp.util.logging.RedwoodConfiguration$Handlers.lambda$static$460(RedwoodConfiguration.java:185)
	... 6 more
Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.util.logging.SLF4JHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at edu.stanford.nlp.util.MetaClass$ClassFactory.construct(MetaClass.java:133)
	at edu.stanford.nlp.util.MetaClass$ClassFactory.<init>(MetaClass.java:200)
	at edu.stanford.nlp.util.MetaClass$ClassFactory.<init>(MetaClass.java:67)
	at edu.stanford.nlp.util.MetaClass.createFactory(MetaClass.java:358)
	... 8 more
Traceback (most recent call last):
  File "main.py", line 147, in <module>
    exit(main(argv))
  File "main.py", line 142, in main
    entities_relations = stanford_ie(filename, verbose, generate_graphviz)
  File "main.py", line 118, in stanford_ie
    assert not java_process.returncode, 'ERROR: Call to stanford_ie exited with a non-zero code status.'`

**Comment by philipperemy** [comment]
It seems that Stanford NLP group has changed some interfaces in the new JAR they provide.

I'm uploading the previous JARs I have from mid-2016 and it seems to work nicely.

Will let you know when it's ready!

**Comment by philipperemy** [comment]
Pull from the project by running : `git pull origin master`

It should work :)

**Comment by philipperemy** [comment]
Feel free to re-open this issue if the problem failed to be solved.
