### ISSUE TITLE
Issue while running the sample code 

### ISSUE THREAD

**Issue by deepaknlp** [philipperemy/Stanford-OpenIE-Python#20]
Hi @philipperemy,

I am getting the following error while executing the sample code:
```
(openie) deepak@nlp-server:~/Stanford-OpenIE-Python$ python main.py -f samples.txt
Text: Barack Obama was born in Hawaii. Richard Manning wrote this sentence..
Starting server with command: java -Xmx8G -cp /home1/deepak/.stanfordnlp_resources/stanford-corenlp-full-2018-10-05/* edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 60000 -threads 5 -maxCharLength 100000 -quiet True -serverProperties corenlp_server-ae5b5964489b4544.props -preload openie
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    for triple in client.annotate(text):
  File "/home1/deepak/Stanford-OpenIE-Python/openie/openie.py", line 39, in annotate
    properties_key=properties_key, properties=properties)
  File "/home1/deepak/anaconda/envs/openie/lib/python3.6/site-packages/stanfordnlp/server/client.py", line 398, in annotate
    r = self._request(text.encode('utf-8'), request_properties, **kwargs)
  File "/home1/deepak/anaconda/envs/openie/lib/python3.6/site-packages/stanfordnlp/server/client.py", line 311, in _request
    self.ensure_alive()
  File "/home1/deepak/anaconda/envs/openie/lib/python3.6/site-packages/stanfordnlp/server/client.py", line 137, in ensure_alive
    raise PermanentlyFailedException("Timed out waiting for service to come alive.")
stanfordnlp.server.client.PermanentlyFailedException: Timed out waiting for service to come alive.
```
I also tried with the java command:
```
java -Xmx8G -cp "/home1/deepak/.stanfordnlp_resources/stanford-corenlp-full-2018-10-05/*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 60000 -threads 5 -maxCharLength 100000 -quiet True -serverProperties corenlp_server-ae5b5964489b4544.props -preload openie
[main] INFO CoreNLP - --- StanfordCoreNLPServer#main() called ---
[main] INFO CoreNLP - setting default constituency parser
[main] INFO CoreNLP - warning: cannot find edu/stanford/nlp/models/srparser/englishSR.ser.gz
[main] INFO CoreNLP - using: edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz instead
[main] INFO CoreNLP - to use shift reduce parser download English models jar from:
[main] INFO CoreNLP - http://stanfordnlp.github.io/CoreNLP/download.html
Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: argsToProperties could not read properties file: corenlp_server-ae5b5964489b4544.props
	at edu.stanford.nlp.util.StringUtils.argsToProperties(StringUtils.java:1011)
	at edu.stanford.nlp.util.StringUtils.argsToProperties(StringUtils.java:927)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.<init>(StanfordCoreNLPServer.java:196)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.main(StanfordCoreNLPServer.java:1477)
Caused by: java.io.IOException: Unable to open "corenlp_server-ae5b5964489b4544.props" as class path, filename or URL
	at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:480)
	at edu.stanford.nlp.io.IOUtils.readerFromString(IOUtils.java:617)
	at edu.stanford.nlp.util.StringUtils.argsToProperties(StringUtils.java:1002)
	... 3 more
[Thread-0] INFO CoreNLP - CoreNLP Server is shutting down.
```
Java command without -serverProperties however it could not load the openie
```
java -Xmx8G -cp "/home1/deepak/stanfordnlp_resources/stanford-corenlp-full-2018-10-05/*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9001 -timeout 60000 -threads 5 -maxCharLength 100000 -quiet True  -preload openie
[main] INFO CoreNLP - --- StanfordCoreNLPServer#main() called ---
[main] INFO CoreNLP - setting default constituency parser
[main] INFO CoreNLP - warning: cannot find edu/stanford/nlp/models/srparser/englishSR.ser.gz
[main] INFO CoreNLP - using: edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz instead
[main] INFO CoreNLP - to use shift reduce parser download English models jar from:
[main] INFO CoreNLP - http://stanfordnlp.github.io/CoreNLP/download.html
[main] INFO CoreNLP -     Threads: 5
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator openie
[main] INFO edu.stanford.nlp.naturalli.ClauseSplitter - Loading clause splitter from edu/stanford/nlp/models/naturalli/clauseSearcherModel.ser.gz ... done [0.0136 seconds]
[main] ERROR CoreNLP - Could not pre-load annotators in server; encountered exception:
java.lang.IllegalArgumentException: annotator "openie" requires annotation "SentenceIndexAnnotation". The usual requirements for this annotator are: tokenize,ssplit,pos,lemma,depparse,natlog
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:260)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:192)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:188)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.main(StanfordCoreNLPServer.java:1505)
[main] INFO CoreNLP - Starting server...
[main] INFO CoreNLP - StanfordCoreNLPServer listening at /0:0:0:0:0:0:0:0:9001
```
I request you to please help me in this regard.

**Comment by philipperemy** [comment]
@deepaknlp I can confirm it works on my server with python3.6.

Have a look at this: https://github.com/stanfordnlp/stanza/issues/245

It might solve your problem. Maybe something like this will work:

```
unset http_proxy
unset https_proxy
```

**Comment by deepaknlp** [comment]
Hi, @philipperemy thank you for the quick response.
I tried with `unset` but did not work.
It should run via command line but alas! I am getting the error there also. As you can see in my previous post.

**Comment by philipperemy** [comment]
Do you have full access to your machine is it a machine that is hosted somewhere else like in a university? It seems it's a coreNLP problem rather than a problem arising from this repository.
Your problem is that you can't start the server. Something is blocking it from running.
You should try to re-install from scratch and try running that locally on your Linux/Mac laptop.

**Comment by deepaknlp** [comment]
Yes @philipperemy my machine is hosted in a university. I will try to resolve it on some other machine. Thank you for your help.

**Comment by philipperemy** [comment]
@deepaknlp good luck! I'm sure you'll make it work :)

**Comment by meteorlin** [comment]
I add `['tokenize','ssplit','pos','lemma','ner','depparse','natlog','openie']` to the "annotation" param of `openie.py:44` and it finally works. The final code is like (I set the memory down to "3G" or the JVM cannot be launched.):
```python
CoreNLPClient(annotators=['tokenize','ssplit','pos','lemma','ner','depparse','natlog','openie'], memory='3G', *args, **kwargs)
```
It refers from [stanza#865](https://github.com/stanfordnlp/stanza/issues/865#issuecomment-955949359)
