### ISSUE TITLE
Can not get feedback from Sever

### ISSUE THREAD

**Issue by 1171-jpg** [philipperemy/stanford-openie-python#61]
I installed the environment and ran the demo code.  However, I can not get the feedback from the client. Is there any issue with my set up?
![image](https://github.com/philipperemy/stanford-openie-python/assets/57554286/78fc2215-06d8-4420-8c25-1c38b50b4beb)

**Comment by philipperemy** [comment]
Do you have `java` installed properly?

https://github.com/philipperemy/stanford-openie-python?tab=readme-ov-file#installation

**Comment by KarthikRaju391** [comment]
I have java installed:

```
$ java -version
openjdk version "24-loom" 2025-03-18
OpenJDK Runtime Environment (build 24-loom+7-60)
OpenJDK 64-Bit Server VM (build 24-loom+7-60, mixed mo
de, sharing)
```

should I use an older java runtime?

**Comment by KarthikRaju391** [comment]
even after setting up java 8, the server isn't starting:

```
Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: argsToProperties could not read properties f
ile: corenlp_server-8090116e1a084988.props
        at edu.stanford.nlp.util.StringUtils.argsToProperties(StringUtils.java:1060)
        at edu.stanford.nlp.util.StringUtils.argsToProperties(StringUtils.java:973)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.<init>(StanfordCoreNLPServer.java:183)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.launchServer(StanfordCoreNLPServer.java:1590)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.main(StanfordCoreNLPServer.java:1644)
Caused by: java.io.IOException: Unable to open "corenlp_server-8090116e1a084988.props" as class path, filename
or URL
        at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:501)
        at edu.stanford.nlp.io.IOUtils.readerFromString(IOUtils.java:634)
        at edu.stanford.nlp.util.StringUtils.argsToProperties(StringUtils.java:1051)
        ... 4 more
[Thread-0] INFO CoreNLP - CoreNLP Server is shutting down.
```

I am trying to start the server manually here because when the python library tries to start the server automatically, it doesn't do `-cp "<filepath">` and instead just does `-cp <filepath`
